### PR TITLE
Switch from Travis to GitHub Actions for CI

### PR DESCRIPTION
**Pull request by DazWorrall**
There is a legit failure here that I will leave to proper maintainers to look at. Also I removed the `bundler` development dependency as it was causing issues, and I don't think it does much for us at this point?

### CODE REVIEW

**Comment by DazWorrall** [comment]
Oh, no failures this time 🤷 https://github.com/DazWorrall/frozen_record/actions/runs/425911261

**Comment by ChrisBr** [comment]
image

You probably saw this already?

**Review by ChrisBr — APPROVED** [review]
Not a maintainer of this repository but LGTM. Good idea to 🧹  Travis.

**Comment by DazWorrall** [comment]
> You probably saw this already?

I did - I'm only using official GitHub actions in the workflow, so I expect it will be fine.

cc @byroot for 2021 👀

**Comment by casperisfine** [comment]
Thanks!

**Pull request merged**
